apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fusionauth
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: auth.aaron-miller.me
      http:
        paths:
        - backend:
            serviceName: fusionauth
            servicePort: 9011
